run:
  timeout: 10m
linters:
  enable:
    - copyloopvar
    - errcheck
    - errname
    - errorlint
    - goconst
    - gofmt
    - gofumpt
    - govet
    - misspell
    - nilerr
    - staticcheck
    - unconvert
    - unused
