FROM debian:12.7-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    ca-certificates; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    groupadd -r beekeeper --gid 999; \
    useradd -r -g beekeeper --uid 999 --no-log-init -m beekeeper;

# make sure mounted volumes have correct permissions
RUN mkdir -p /home/beekeeper/.beekeeper && chown 999:999 /home/beekeeper/.beekeeper

COPY ./tmp/beekeeper /usr/local/bin/beekeeper

USER beekeeper
WORKDIR /home/beekeeper
VOLUME /home/beekeeper/.beekeeper

ENTRYPOINT ["beekeeper"]
