bee-configs:
  light-node:
    _inherit: default
    full-node: false

node-groups:
  light-node:
    _inherit: default
    image: ethersphere/bee:latest
    image-pull-policy: IfNotPresent
    persistence-enabled: false
