# bee config for restricted nodes
bee-configs:
  restricted:
    _inherit: default
    restricted: true
    admin-username: test
    admin-password: test

# node groups for restricted nodes
node-groups:
  restricted:
    _inherit: default
    image: ethersphere/bee:latest
    image-pull-policy: Always
    persistence-enabled: false
