# bee config for restricted nodes
bee-configs:
  restricted:
    _inherit: default
    restricted: true
    token-encryption-key: testtest
    admin-password: $2a$12$Ltg3M2W53Xv9wwJ2.iAv4e4gWELrrr8D2dYat7wNdY2xArdmOSL1i

# node groups for restricted nodes
node-groups:
  restricted:
    _inherit: default
    image: ethersphere/bee:latest
    image-pull-policy: Always
    persistence-enabled: true
