# bee config for restricted nodes
bee-configs:
  restricted:
    _inherit: default
    restricted: true
    admin-username: test
    admin-password: $2a$12$4q3T8gCc1nnPcar58OEAxeuclim/urcLpcwNEPnKcO9YT/2/sOA3m

# node groups for restricted nodes
node-groups:
  restricted:
    _inherit: default
    image: anatollupacescu/restricted:latest
    image-pull-policy: Always
    persistence-enabled: false
